--- #YAML:1.0
name:                AI-Pathfinding-SMAstar
version:             0.07
abstract:            Simplified Memory-bounded A* Search
license:             ~
author:              
    - Matthias Beebe <mbeebe@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    Tree::AVL:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
